type: specs.intershop.com/v1beta/migrate
migrator: com.intershop.customization.migration.environment.CreateEnvironmentExampleFiles
message: "feat: (re-)create environment.bat.example, icm.properties.example, clean.bat"
